### ISSUE TITLE
FileNotFoundException on connect

### ISSUE THREAD

**Issue by E-Mans-Application** [CenterDevice/MiniFSWatcher#10]
Hello,

A FileNotFound Exception is thrown when I call Connect on the EventWatcher (the code is VB.NET not C#):

```
  Dim filewatcher As New EventWatcher() With {
                .OnRenameOrMove = AddressOf FileRenamed,
                .OnChange = AddressOf FileChanged,
                 .OnCreate = AddressOf FileChanged,
                .OnDelete = AddressOf FileDeleted,
                .Tag = path,
                .AggregateEvents = True
             }
        filewatcher.Connect() 'throws exception
        filewatcher.WatchPath(path) 'not reached
```

System.IO.FileNotFoundException
  HResult=0x80070002
  Source=mscorlib
 Stacktrace=
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at CenterDevice.MiniFSWatcher.FilterConnector.Connect()
   atCenterDevice.MiniFSWatcher.EventWatcher.Connect()
   [...]
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by trentech** [comment]
Same error..no solution..

**Comment by resolvethis** [comment]
Does the path point to a restricted resource? It is years ago, but I think I had same/similar issue with a number of paths on Windows. You could try with another path?

**Comment by ghost** [comment]
same problem, but with C# instead of VB.NET

**Comment by xNala** [comment]
I know this is a super old issue 
@trentech @E-Mans-Application 

But if you read the ReadMe

It says both the kernel driver and usermode application are needed
Have you made sure your kernel driver is loaded?
